name: "Bug Report"
description: "Create a report to help us improve"
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        This is a bug tracker of Flame-Route. Use search to check whether your issue has been already reported and perhaps solved.
        
        To submit a bug report, fill the form below. Provide as much as possible information about the encountered issue. We may request extended information such as `strace` logs if considered necessary. This will help the maintainers to understand the problem correctly and provide a solution. 

        Make sure that your logs do not leak sensitive information (passwords, API keys, etc). Be patient, do not expect that issue could get resolved immediately.

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: Describe the bug in detail
      placeholder: Enter description here
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Enter the steps to reproduce the bug
      placeholder: Enter steps here
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What was the expected behavior?
      placeholder: Enter expected behavior here
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What was the actual behavior?
      placeholder: Enter actual behavior here
    validations:
      required: true

  - type: input
    id: triplet
    attributes:
      label: Platform Triplet
      description: Enter your platform triplet
      placeholder: e.g. x86-linux-gnu
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Enter any additional information related to the bug
      placeholder: Enter additional information here
    validations:    
      required: false

